class ConsultationsController < ApplicationController
  before_action :set_consultation, only: [:update, :destroy]
  before_action :check_authorization

  # GET /consultations
  def index
    @consultations = Consultation.all.map{|m| [m.id, m] }.to_h
    respond_to do |format|
      format.html { render :action => "index" }
      format.json { render :json => @consultationsx}
    end
  end

  # POST /consultations
  def create
    @consultation = Consultation.new(consultation_params)

    if @consultation.save
      render :json => @consultation
    else
      render json: @consultation.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /consultations/1
  def update
    if @consultation.update(consultation_params)
      render json: @consultation
    else
      render json: @consultation.errors, status: :unprocessable_entity
    end
  end

  # DELETE /consultations/1
  def destroy
    render json: @consultation.destroy
  end

  # GET /consultations/search
  # This action is included as a placeholder for actual search logic.
  # The react component generated by default will send a search string in params[:search_text]
  def search
    render json: Consultation.first(10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultation
      @consultation = Consultation.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def consultation_params
      params.require(:consultation).permit(:description, :dates, :consultants, :minutes, :consultation_category_id, :ccrc_id)
    end

    def check_authorization
      authorize Consultation
    end
end
