class PersonScantronAppointmentsController < ApplicationController
  before_action :set_person_scantron_appointment, only: [:update, :destroy]
  before_action :check_authorization

  # GET /person_scantron_appointments
  def index
    @person_scantron_appointments = PersonScantronAppointment.all.map{|m| [m.id, m] }.to_h
    respond_to do |format|
      format.html { render :action => "index" }
      format.json { render :json => @person_scantron_appointmentsx}
    end
  end

  # POST /person_scantron_appointments
  def create
    @person_scantron_appointment = PersonScantronAppointment.new(person_scantron_appointment_params)

    if @person_scantron_appointment.save
      render :json => @person_scantron_appointment
    else
      render json: @person_scantron_appointment.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /person_scantron_appointments/1
  def update
    if @person_scantron_appointment.update(person_scantron_appointment_params)
      render json: @person_scantron_appointment
    else
      render json: @person_scantron_appointment.errors, status: :unprocessable_entity
    end
  end

  # DELETE /person_scantron_appointments/1
  def destroy
    render json: @person_scantron_appointment.destroy
  end

  # GET /person_scantron_appointments/search
  # This action is included as a placeholder for actual search logic.
  # The react component generated by default will send a search string in params[:search_text]
  def search
    render json: PersonScantronAppointment.first(10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person_scantron_appointment
      @person_scantron_appointment = PersonScantronAppointment.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def person_scantron_appointment_params
      params.require(:person_scantron_appointment).permit(:person_id, :scantron_appointment_id)
    end

    def check_authorization
      authorize PersonScantronAppointment
    end
end
