class PersonGroupsController < ApplicationController
  before_action :set_person_group, only: [:update, :destroy]

  # GET /person_groups
  def index
    @person_groups = PersonGroup.all.map{|m| [m.id, m.with_associations] }.to_h
    respond_to do |format|
      format.html { render :action => "index" }
      format.json { render :json => @person_groupsx}
    end
  end

  # POST /person_groups
  def create
    @person_group = PersonGroup.new(person_group_params)

    if @person_group.save
      render :json => @person_group.with_associations
    else
      render json: @person_group.errors, status: :unprocessable_entity
    end
  end

  # PATCH/PUT /person_groups/1
  def update
    if @person_group.update(person_group_params)
      render json: @person_group.with_associations
    else
      render json: @person_group.errors, status: :unprocessable_entity
    end
  end

  # DELETE /person_groups/1
  def destroy
    render json: @person_group.destroy
  end

  # GET /person_groups/search
  # This action is included as a placeholder for actual search logic.
  # The react component generated by default will send a search string in params[:search_text]
  def search
    render json: PersonGroup.first(10)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person_group
      @person_group = PersonGroup.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def person_group_params
      params.require(:person_group).permit(:group_id, :person_id, :role, :start, :end)
    end
end
